spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twotwo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 또는 create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
