spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://RDS-엔드포인트:5432/twotwo
    username: ${username}
    password: ${password}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

