name: 빌드 테스트

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 가져오기
        uses: actions/checkout@v3

      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 실행 권한 부여
        run: chmod +x gradlew

      - name: gradle 빌드
        run: ./gradlew clean build -x test

      - name: 빌드 생성 확인
        run: ls -lah build/libs/
